# Test - 1

In [2]:
import os
os.environ["MODIN_ENGINE"] = "dask"
import pandas as pd
import polars as pl 
import dask.dataframe as dd
import vaex as vx
import modin.pandas as md
from dask.distributed import Client

import time
import numpy as np

import shutil

In [3]:
PATH_DATA = '../../df-showdown-data/'
TEMP_PATH = PATH_DATA+'temp/'
PATH_OUTPUT = '../output/'

In [4]:
# https://modin.readthedocs.io/en/stable/getting_started/why_modin/out_of_core.html
cli = Client()
cli

## Input

In [4]:
all_sla = {}
all_sla['pandas'] = []
all_sla['modin_dask'] = []
all_sla['polars'] = []
all_sla['dask'] = []
all_sla['vaex'] = []
all_sla['rows_cnt_in_million'] = []

for i in range(8):
    fn = 'data_{}.csv'.format(i)
    
    start = time.perf_counter()
    dtemp1 = pd.read_csv(PATH_DATA+fn)
    end = time.perf_counter() - start
    all_sla['pandas'].append(end)

    nrow = round(dtemp1.shape[0]/1000000,2)
    all_sla['rows_cnt_in_million'].append(nrow)
    del dtemp1

    start = time.perf_counter()
    dtemp1 = md.read_csv(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['modin_dask'].append(end)

    start = time.perf_counter()
    dtemp1 = pl.read_csv(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['polars'].append(end)

    start = time.perf_counter()
    dtemp1 = dd.read_csv(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask'].append(end)

    start = time.perf_counter()
    dtemp1 = vx.open(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['vaex'].append(end)

    print(i)

all_sla_csv = all_sla.copy()

NameError: name 'time' is not defined

In [6]:
df_sla1 = pd.DataFrame(all_sla_csv)
df_sla1.to_csv(PATH_OUTPUT+'sla_input-csv.csv',index = False)
df_sla1

      pandas  modin_dask     polars      dask      vaex  rows_cnt_in_million
0   0.178754    0.705764   0.016379  0.009245  0.534900                 0.13
1   1.637717    0.731384   0.196539  0.017115  0.064710                 1.42
2   3.852977    1.699110   0.309951  0.023913  0.077952                 3.35
3  11.233249    4.723723   0.902028  0.053444  0.139689                 9.80
4  22.227384    9.377099   1.533448  0.044669  0.292905                19.48
5  41.482275   40.523838   3.394841  0.025541  0.430259                34.95
6  57.862753   96.995424   7.815317  0.170022  0.942417                45.27
7  77.492268  117.707541  10.742652  0.176802  5.121609                58.17

:

In [8]:
all_sla = {}
all_sla['pandas'] = []
all_sla['polars'] = []
all_sla['dask'] = []
all_sla['vaex'] = []
all_sla['rows_cnt_in_million'] = []

i = 0

for i in range(9):
    fn = 'data_{}.parquet'.format(i)

    start = time.perf_counter()
    dtemp1 = pd.read_parquet(PATH_DATA+fn)
    end = time.perf_counter() - start
    all_sla['pandas'].append(end)

    nrow = round(dtemp1.shape[0]/1000000,2)
    all_sla['rows_cnt_in_million'].append(nrow)
    del dtemp1

    start = time.perf_counter()
    dtemp1 = pl.read_parquet(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['polars'].append(end)

    start = time.perf_counter()
    dtemp1 = dd.read_parquet(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask'].append(end)

    start = time.perf_counter()
    dtemp1 = vx.open(PATH_DATA+fn)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['vaex'].append(end)

    print(i)

# del dtemp1
all_sla_parquet = all_sla.copy()

0
1
2
3
4
5
6
7
8

In [9]:
df_sla2 = pd.DataFrame(all_sla_parquet)
df_sla2.to_csv(PATH_OUTPUT+'sla_input-parquet.csv',index = False)
df_sla2

      pandas    polars      dask      vaex  rows_cnt_in_million
0   0.068613  0.009010  0.004118  0.002638                 0.13
1   0.503486  0.071158  0.007462  0.003347                 1.42
2   1.228767  0.161446  0.004157  0.002826                 3.35
3   3.404511  0.451774  0.004453  0.002948                 9.80
4   6.746792  0.964147  0.004339  0.003204                19.48
5  12.065264  1.592193  0.008306  0.004774                34.95
6  15.518818  2.042627  0.006749  0.004805                45.27
7  20.193163  2.637946  0.009993  0.005989                58.17
8  24.059026  3.345513  0.011054  0.005042                71.07

## Output

In [3]:
all_sla = {}
all_sla['pandas'] = []
all_sla['polars'] = []
all_sla['dask_default'] = []
all_sla['dask_single'] = []
all_sla['vaex'] = []
all_sla['rows_cnt_in_million'] = []

for i in range(9):
    fn = 'data_{}.csv'.format(i)

    dtemp1 = pd.read_csv(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.to_csv(TEMP_PATH + 'temp.csv',index=False)
    end = time.perf_counter() - start
    all_sla['pandas'].append(end)

    nrow = round(dtemp1.shape[0]/1000000,2)
    all_sla['rows_cnt_in_million'].append(nrow)
    del dtemp1
    os.remove(TEMP_PATH + 'temp.csv')

    dtemp1 = pl.read_csv(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.write_csv(TEMP_PATH + 'temp.csv')
    end = time.perf_counter() - start
    del dtemp1
    all_sla['polars'].append(end)
    os.remove(TEMP_PATH + 'temp.csv')

    # https://mungingdata.com/dask/ouput-dataframe-single-csv-file/
    dtemp1 = dd.read_csv(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.to_csv(TEMP_PATH + 'temp_dask/',index=False)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask_default'].append(end)
    shutil.rmtree(TEMP_PATH + 'temp_dask/')

    dtemp1 = dd.read_csv(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.compute().to_csv(TEMP_PATH + 'temp.csv',index=False)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask_single'].append(end)
    os.remove(TEMP_PATH + 'temp.csv')

    dtemp1 = vx.open(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.export(TEMP_PATH + 'temp.csv',index=False)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['vaex'].append(end)
    os.remove(TEMP_PATH + 'temp.csv')

    print(i)

all_sla_csv = all_sla.copy()

0
1
2
3
4
5
6
7
8

In [5]:
df_sla1 = pd.DataFrame(all_sla_csv)
df_sla1.to_csv(PATH_OUTPUT+'sla_output-csv.csv',index = False)
df_sla1

,pandas,polars,dask_default,dask_single,vaex,rows_cnt_in_million
0,0.356957,0.019550,0.570437,0.519063,0.590997,0.13
1,4.005358,0.153859,6.146210,5.543378,5.272034,1.42
2,9.433367,0.356694,14.202152,12.520736,12.255931,3.35
3,27.206933,1.021401,43.260226,36.136343,35.468804,9.80
4,54.172915,2.103435,86.041469,72.645858,70.870602,19.48
5,99.253429,4.790633,155.799814,132.698072,129.420755,34.95
6,129.046628,6.588961,201.814062,171.569201,169.241608,45.27
7,166.273420,7.270174,265.502424,229.676252,222.677001,58.17
8,205.499176,8.835024,323.691010,278.244388,269.682794,71.07

In [22]:
all_sla = {}
all_sla['pandas'] = []
all_sla['polars'] = []
all_sla['dask_default'] = []
all_sla['dask_single'] = []
all_sla['vaex'] = []
all_sla['rows_cnt_in_million'] = []

for i in range(9):
    fn = 'data_{}.parquet'.format(i)

    dtemp1 = pd.read_parquet(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.to_parquet(TEMP_PATH + 'temp.parquet',index=False)
    end = time.perf_counter() - start
    all_sla['pandas'].append(end)

    nrow = round(dtemp1.shape[0]/1000000,2)
    all_sla['rows_cnt_in_million'].append(nrow)
    del dtemp1
    os.remove(TEMP_PATH + 'temp.parquet')

    dtemp1 = pl.read_parquet(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.write_parquet(TEMP_PATH + 'temp.parquet')
    end = time.perf_counter() - start
    del dtemp1
    all_sla['polars'].append(end)
    os.remove(TEMP_PATH + 'temp.parquet')

    dtemp1 = dd.read_parquet(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.to_parquet(TEMP_PATH + 'temp_dask_par/')
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask_default'].append(end)
    shutil.rmtree(TEMP_PATH + 'temp_dask_par/')

    dtemp1 = dd.read_parquet(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.compute().to_parquet(TEMP_PATH + 'temp.parquet')
    end = time.perf_counter() - start
    del dtemp1
    all_sla['dask_single'].append(end)
    os.remove(TEMP_PATH + 'temp.parquet')

    dtemp1 = vx.open(PATH_DATA+fn)
    start = time.perf_counter()
    dtemp1.export(TEMP_PATH + 'temp.parquet',index=False)
    end = time.perf_counter() - start
    del dtemp1
    all_sla['vaex'].append(end)
    os.remove(TEMP_PATH + 'temp.parquet')

    print(i)

all_sla_parquet = all_sla.copy()

0
1
2
3
4
5
6
7

:

:

In [1]:
df_sla2 = pd.DataFrame(all_sla_parquet)
df_sla2.to_csv(PATH_OUTPUT+'sla_output-parquet.csv',index = False)
df_sla2

NameError: name 'pd' is not defined